[phases.build]
nixPkgs = ['python311', 'nodejs']
cmds = ['pip install -r requirements.txt']

[phases.setup]
nixPkgs = ['python311']

[staticAssets]
# Skip static assets

[start]
cmd = "python bot.py"
